// Importing and extraction of environment variables
require('dotenv').config()
const { MAILER_HOST, MAILER_PORT, MAILER_USER, MAILER_PASSWORD, DBA_EMAILS } = process.env;
const { Error } = require('./Logs');
// Mailer Import
const nodemailer = require('nodemailer')

// Transport Object
let transport = nodemailer.createTransport({
    host: MAILER_HOST,
    port: MAILER_PORT,
    auth: {
        user: MAILER_USER, //generated by Mailtrap stored in .env
        pass: MAILER_PASSWORD //generated by Mailtrap stored in .env
    }
})

module.exports =
    /**
     * Sends Email
     * @param {string} subject 
     * @param {string} text 
     * @param {string} html 
     */
    function SendEmail(subject, text, html) {
        // Mail Option 
        let mailOptions = {
            from: `"Member Management System - Server"<${MAILER_USER}>`,
            to: DBA_EMAILS,
            subject,
            text,
            html
        }

        // Sends Email
        transport.sendMail(mailOptions, (error, info) => {
            if (error)
                Error.log(error)
        })
    }